version: 2.1

orbs:
  win: circleci/windows@2.4.1
  aws-cli: circleci/aws-cli@2.0.3
  gh: circleci/github-cli@1.0.4

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: '14.17.5'
    root_tap_tests:
      type: boolean
      default: false
    jest_tests:
      type: boolean
      default: false
    acceptance_tests:
      type: boolean
      default: false
    system_tests:
      type: boolean
      default: false
    package_tests:
      type: boolean
      default: false
  working_directory: ~/snyk

commands:
  install_project_dependencies:
    parameters:
      os:
        type: string
        default: 'linux'
      node_version:
        type: string
      npm_version:
        type: string
        default: '7.21.1'
    steps:
      - restore_cache:
          name: Restoring NPM cache
          keys:
            - npm-cache-v1-{{ arch }}-node<< parameters.node_version >>-npm<< parameters.npm_version >>-{{ checksum "package-lock.json" }}
      - when:
          condition:
            equal: ['win/default', << parameters.os >>]
          steps:
            run:
              name: Installing NPM
              command: npm install -g npm@<< parameters.npm_version >>
      - when:
          condition:
            not:
              equal: ['win/default', << parameters.os >>]
          steps:
            run:
              name: Installing NPM
              command: sudo npm install -g npm@<< parameters.npm_version >>
      - run:
          name: Configuring NPM
          command: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
      - run:
          name: Installing project dependencies
          command: npm ci
      - when:
          condition:
            equal: ['win/default', << parameters.os >>]
          steps:
            - save_cache:
                name: Saving NPM cache
                key: npm-cache-v1-{{ arch }}-node<< parameters.node_version >>-npm<< parameters.npm_version >>-{{ checksum "package-lock.json" }}
                paths:
                  - ~\AppData\Local\npm-cache
      - when:
          condition:
            not:
              equal: ['win/default', << parameters.os >>]
          steps:
            - save_cache:
                name: Saving NPM cache
                key: npm-cache-v1-{{ arch }}-node<< parameters.node_version >>-npm<< parameters.npm_version >>-{{ checksum "package-lock.json" }}
                paths:
                  - ~/.npm
  build_project:
    steps:
      - run:
          name: Building project
          command: npm run build:prod
      - persist_to_workspace:
          root: .
          paths:
            - dist/
            - packages/*/dist
            - pysrc
  install_sdks_windows:
    steps:
      - restore_cache:
          name: Restoring Chocolatey cache
          keys:
            - chocolatey-cache-v2-{{ arch }}-{{ checksum ".circleci/chocolatey.config" }}
      - run:
          name: Installing SDKs
          command: choco install .circleci/chocolatey.config --no-progress
      - save_cache:
          name: Saving Chocolatey cache
          key: chocolatey-cache-v2-{{ arch }}-{{ checksum ".circleci/chocolatey.config" }}
          paths:
            - ~\AppData\Local\Temp\chocolatey
  install_sdks_linux:
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
      - restore_cache:
          name: Restoring SDKMAN cache
          keys:
            - sdkman-cache-v2-{{ arch }}-{{ checksum ".circleci/install-sdks-linux.sh" }}
      - run:
          name: Installing SDKs
          command: ./.circleci/install-sdks-linux.sh
      - save_cache:
          name: Saving SDKMAN cache
          key: sdkman-cache-v2-{{ arch }}-{{ checksum ".circleci/install-sdks-linux.sh" }}
          paths:
            - ~/.sdkman/archives
  install_node_windows:
    parameters:
      node_version:
        type: string
    steps:
      - run:
          name: Removing pre-installed NodeJS
          command: |
            $current_node_version = node --version
            nvm uninstall $current_node_version
      - run:
          name: Installing NodeJS
          command: choco install nodejs --version=<< parameters.node_version >> --no-progress
  install_shellspec:
    description: Install Shellspec
    steps:
      - run: curl -fsSL https://git.io/shellspec | sh -s -- -y
      - run: sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
      - run: sudo apt-get install jq

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: large
    steps:
      - checkout
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - build_project
  regression-test:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_sdks_linux
      - install_shellspec
      - run: sudo apt-get install python-pip
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: ~/snyk
      - run: npm run lint
      - run:
          name: npm install for fixture project
          working_directory: ~/snyk/test/fixtures/basic-npm
          command: npm install
      - run:
          name: prune dependencies
          command: node ./release-scripts/prune-dependencies-in-packagejson.js
      - run: mkdir ./dist-pack
      - run:
          name: pack
          command: npm pack ..
          path: ./dist-pack
      - run:
          name: Install packed Snyk globally
          command: find . -name '*.tgz' | xargs sudo npm install -g
      - run:
          name: Run shellspec
          working_directory: ~/snyk/test/smoke
          command: |
            echo "Checkout the README in test/smoke folder for more details about this step"
            unset SNYK_API
            unset SNYK_API_KEY
            shellspec -f d -e REGRESSION_TEST=1
  test-windows:
    <<: *defaults
    executor: win/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - install_node_windows:
          node_version: << parameters.node_version >>
      - install_sdks_windows
      - install_project_dependencies:
          os: win/default
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: ~/snyk
      - run:
          name: Add Snyk Token to Snyk Config
          command: node ./bin/snyk config set "api=$env:SNYK_API_KEY"
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Run Package unit tests
                command: npm run test:packages-unit -- --ci
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Run Package acceptance tests
                command: npm run test:packages-acceptance -- --ci
      - when:
          condition: << parameters.root_tap_tests >>
          steps:
            - run:
                name: Run "Root" tap tests
                command: npm run test:test
      - when:
          condition: << parameters.jest_tests >>
          steps:
            - run:
                name: Run Jest tests in root (to remove)
                command: npm run test:jest -- --ci
            - run:
                name: Run Jest Unit Tests
                command: npm run test:jest-unit -- --ci
            - run:
                name: Run Jest System Tests
                command: npm run test:jest-system -- --ci
            - run:
                name: Run Jest Acceptance Tests
                command: npm run test:jest-acceptance -- --ci
      - when:
          condition: << parameters.acceptance_tests >>
          steps:
            - run:
                name: Run Acceptance tests
                command: npm run test:acceptance-windows
      - when:
          condition: << parameters.system_tests >>
          steps:
            - run:
                name: Run System tests
                command: npm run test:system
  test-linux:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: large
    steps:
      - checkout
      - install_sdks_linux
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: ~/snyk
      - run:
          name: Add Snyk Token to Snyk Config
          command: node ./bin/snyk config set "api=${SNYK_API_KEY}"
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Run Package unit tests
                command: npm run test:packages-unit -- --ci
      - when:
          condition: << parameters.package_tests >>
          steps:
            - run:
                name: Run Package acceptance tests
                command: npm run test:packages-acceptance -- --ci
      - when:
          condition: << parameters.root_tap_tests >>
          steps:
            - run:
                name: Run "Root" tap tests
                command: npm run test:test
      - when:
          condition: << parameters.jest_tests >>
          steps:
            - run:
                name: Run Jest tests in root (to remove)
                command: npm run test:jest -- --ci
            - run:
                name: Run Jest Unit Tests
                command: npm run test:jest-unit -- --ci
            - run:
                name: Run Jest System Tests
                command: npm run test:jest-system -- --ci
            - run:
                name: Run Jest Acceptance Tests
                command: npm run test:jest-acceptance -- --ci
      - when:
          condition: << parameters.acceptance_tests >>
          steps:
            - run:
                name: Run Acceptance tests
                command: npm run test:acceptance
      - when:
          condition: << parameters.system_tests >>
          steps:
            - run:
                name: Run System tests
                command: npm run test:system
  dev-release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: large
    steps:
      - checkout
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: ~/snyk
      - run:
          name: Update package versions
          command: ./release-scripts/update-dev-versions.sh
      - run:
          name: Install osslsigncode
          command: sudo apt-get install -y osslsigncode
      - run:
          name: prune dependencies
          command: node ./release-scripts/prune-dependencies-in-packagejson.js
      - run:
          name: Create Binaries
          command: |
            cat package.json
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validate binary release checksums
          working_directory: ~/snyk/binary-releases
          command: |
            ../release-scripts/validate-checksums.sh
      - run: mkdir ./dist-pack
      - run:
          name: pack
          command: npm pack ..
          path: ./dist-pack
      - store_artifacts:
          path: ./dist-pack
  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    resource_class: small
    steps:
      - checkout
      - run:
          name: Should I release?
          command: ./release-scripts/should-i-release.sh
      - gh/setup:
          token: GH_TOKEN
          version: 1.9.2
      - aws-cli/install:
          version: 2.2.32
      - run:
          name: Install osslsigncode
          command: sudo apt-get install -y osslsigncode
      - install_project_dependencies:
          node_version: << parameters.node_version >>
      - attach_workspace:
          at: ~/snyk
      - run:
          name: prune dependencies
          command: node ./release-scripts/prune-dependencies-in-packagejson.js
      - run:
          name: Update package versions
          command: ./release-scripts/update-versions.sh
      - run:
          name: Make git ignore changes relating to version updates
          command: |
            git update-index --skip-worktree -- ./lerna.json
            git update-index --skip-worktree -- ./package.json
            git update-index --skip-worktree -- ./packages/snyk-protect/package.json
      - run:
          name: Lerna Publish
          command: |
            npx lerna publish minor --yes --no-push --no-git-tag-version --exact
      - run:
          name: Create Binaries
          command: |
            ./release-scripts/make-binaries.sh
            ls -la ./binary-releases
      - store_artifacts:
          path: ./binary-releases
      - run:
          name: Validate binary release checksums
          working_directory: ~/snyk/binary-releases
          command: |
            ../release-scripts/validate-checksums.sh
      - run:
          name: Generate Release Notes
          command: |
            npx conventional-changelog-cli -p angular -l -r 1 > RELEASE_NOTES.txt
      - run:
          name: Upload Artifacts
          command: ./release-scripts/upload-artifacts.sh
      - run:
          name: Handle failed CLI release
          command: |
            ./release-scripts/handle-failed-release.sh
          when: on_fail

workflows:
  version: 2
  test_and_release:
    jobs:
      - build:
          name: Build
          context: nodejs-install
      - regression-test:
          name: Regression Test
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
      - dev-release:
          name: Dev Release
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master

      - test-windows:
          name: Windows, Node v14.17.5 - Packages, Jest, System tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          jest_tests: true
          system_tests: true
          package_tests: true
      - test-windows:
          name: Windows, Node v14.17.5 - Acceptance tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          acceptance_tests: true
      - test-windows:
          name: Windows, Node v14.17.5 - "Root" tap tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          root_tap_tests: true

      - test-linux:
          name: Linux, Node v<< matrix.node_version >> - Packages, Jest, System tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          matrix:
            parameters:
              node_version: ['10.24.1', '12.22.5', '14.17.5']
          jest_tests: true
          system_tests: true
          package_tests: true
      - test-linux:
          name: Linux, Node v<< matrix.node_version >> - Acceptance tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          matrix:
            parameters:
              node_version: ['10.24.1', '12.22.5', '14.17.5']
          acceptance_tests: true
      - test-linux:
          name: Linux, Node v<< matrix.node_version >> - "Root" tap tests
          context: nodejs-install
          requires:
            - Build
          filters:
            branches:
              ignore:
                - master
          matrix:
            parameters:
              node_version: ['10.24.1', '12.22.5', '14.17.5']
          root_tap_tests: true
      - release:
          name: Release
          context: nodejs-app-release
          filters:
            branches:
              only:
                - master
          requires:
            - Build
