name: 'Danger Zone'
on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/danger/danger-js/issues/557#issuecomment-664851950
          DANGER_DISABLE_TRANSPILATION: true
