name: Copy CLI help from snyk/user-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' # Mon-Fri at 12

jobs:
  build:
    name: Copy CLI help from snyk/user-docs
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh auth setup-git
          git config --global user.email "noreply@snyk.io"
          git config --global user.name "$GITHUB_ACTOR"
          gh repo clone snyk/snyk cli -- --depth=1 --quiet
          gh repo clone snyk/user-docs docs -- --depth=1 --quiet
          git -C ./cli checkout -b docs/automatic-gitbook-update

          cp ./docs/docs/features/snyk-cli/commands/*.md ./cli/help/cli-commands/

          if [[ $(git -C ./cli status --porcelain) ]]; then
            echo "Documentation changes detected, opening a PR"
            cd ./cli
            git --no-pager diff --name-only
            git add .
            git commit -m "docs: synchronized help from snyk/user-docs"
            git push --force --set-upstream origin docs/automatic-gitbook-update
            gh pr create --title="Synchronizing CLI help from user-docs" --body="Automatic PR controlled by GitHub Action" --head docs/automatic-gitbook-update
          else
            echo "No documentation changes detected, exiting"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
